import Provider from "@/context/provider";
import Navbar from "./(components)/(global)/Nav";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "DDC OABS",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <Provider>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
